[package]
name = "rebase-snap"
version = "1.5.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
build = "../../build.rs"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[dependencies]
libc = "0.2.147"
thiserror = "1.0.40"
tracing = { version = "0.1.37", default-features = false, features = ["max_level_debug", "attributes"] }

utils = { path = "../utils" }
